Time values should be unspecified when converting Date using ToDateTime
cqframework/cql-execution pull request #263
Opened 2022-02-10 20:38 UTC by dczulada

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository.
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [ ] This pull request describes why these changes were made
- [ ] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass
- [ ] Code coverage has not gone down and all code touched or added is covered.
- [ ] Code passes lint and prettier (hint: use `yarn run test:plus` to run tests, lint, and prettier)
- [ ] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [ ] `cql4browsers.js` built with `yarn run build:browserify` if source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2022-02-24 16:41 UTC, p9g commented
Related to errata in CQL spec https://jira.hl7.org/browse/FHIR-35869

2022-03-07 22:28 UTC, cmoesel requested changes
Thanks for this fix, @dczulada!  Everything seems to work great (and as expected).  I just found a few places where a comment and/or test expression or variable name needs to be changed.

2022-03-07 22:28 UTC, cmoesel commented on src/datatypes/datetime.ts
> +      return new DateTime(this.year, this.month, this.day, null, null, null, null);
Line 1178 above (which GitHub will not let me directly comment on) says:
```ts
// from the spec: the result will be a DateTime with the time components set to zero,
```

That comment is now out of sync w/ the implementation.  Can you update it to reflect the correct behavior? It should read like this now:
```ts
// from the spec: the result will be a DateTime with the time components unspecified,
```

Also, while you're at it, could you fix the typo on line 1180 (`acheived`)?

2022-03-07 22:28 UTC, cmoesel commented on test/elm/comparison/comparison-test.ts
> +    this.dateAndDateTimeNull.exec(this.ctx).should.be.true();
The name of the CQL expression (and variable here) is now out of sync w/ the expectation.  Now that this returns `true`, the CQL expression should be `DateAndDateTimeTrue` (and corresponding variable here should be `dateAndDateTimeTrue`).

All of the test expressions and variables need to be checked and fixed to ensure their name still matches the expectation. (So I won't comment on anymore like this).

2022-03-09 20:15 UTC, cmoesel approved these changes
Looks good to me!  Thanks, @dczulada!

2022-03-09 20:54 UTC, mgramigna approved these changes
Looks good and passed all my tests!

2022-03-09 21:26 UTC, merged