Do not perform tz offset with precision of year, month and day
cqframework/cql-execution pull request #264
Opened 2022-02-22 19:46 UTC by dczulada

https://cql.hl7.org/09-b-cqlreference.html#same-as-1
When comparing DateTime values with different timezone offsets, implementations should normalize to the timezone offset of the evaluation request timestamp, but only when the comparison precision is hours, minutes, seconds, or milliseconds.

Pull requests into cql-execution require the following.
Submitter and reviewer should ✔ when done.
For items that are not-applicable, mark "N/A" and ✔.

[CDS Connect](https://cds.ahrq.gov/cdsconnect) and [Bonnie](https://github.com/projecttacoma/bonnie) are the main users of this repository.
It is strongly recommended to include a person from each of those projects as a reviewer.

**Submitter:**
- [ ] This pull request describes why these changes were made
- [ ] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass
- [ ] Code coverage has not gone down and all code touched or added is covered.
- [ ] Code passes lint and prettier (hint: use `npm run test:plus` to run tests, lint, and prettier)
- [ ] All dependent libraries are appropriately updated or have a corresponding PR related to this change
- [ ] `cql4browsers.js` built with `npm run build:browserify` if source changed.

**Reviewer:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2022-03-07 23:00 UTC, cmoesel requested changes
Thanks @dczulada!  This is technically correct, but I have one small suggestion that I'd like you to consider.  Let me know if you disagree or have any questions!

2022-03-09 22:11 UTC, mgramigna commented
This passed all my test cases as well. Just needs a rebase since #263 was merged

2022-03-10 14:25 UTC, mgramigna approved these changes

2022-03-10 18:27 UTC, cmoesel approved these changes
Looks good -- and code coverage increased.  Yay!

2022-03-10 18:27 UTC, merged