Fix tuple equality with null values
cqframework/cql-execution pull request #327
Opened 2024-10-23 12:08 UTC by cmoesel

Previously, if tuples had the same fields, and at least one field had a null value on one tuple and a non-null value on the other, then:
* if the null/non-null field came after a field with different values, it returned false (which is correct)
* if the null/non-null field came before a field with different values, it returned null (which is incorrect)

Now it will return the correct answer regardless of where the null/non-null field is.

_NOTE: This PR does not fix npm audit issues, as those have already been fixed in #326. As a result, this should be merged _after_ #326.

**Submitter:**

- [x] This pull request describes why these changes were made
- [x] Code diff has been done and been reviewed (it does not contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
- [x] Code passes lint and prettier (hint: use `npm run test:plus` to run tests, lint, and prettier)
- [x] All dependent libraries are appropriately updated or have a corresponding PR related to this change - N/A
- [x] `cql4browsers.js` built with `npm run build:browserify` if source changed.

**Reviewer:**

Name:

- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2025-03-30 23:51 UTC, hossenlopp approved these changes
Looks good and I don't foresee any issues with this after a rebase.

2025-03-31 18:12 UTC, elsaperelli approved these changes
Lgtm!

2025-03-31 18:17 UTC, hossenlopp requested changes
A few more suggested tests from when I attempted to "break" the code.

2025-03-31 18:17 UTC, hossenlopp commented on test/util/comparison-test.ts
> +    should(equals({ a: 1, b: 'bee', c: 'sea' }, { a: 1, b: null, c: 'sea' })).be.null();
```suggestion
    should(equals({ a: 1, b: 'bee', c: 'sea' }, { a: 1, b: null, c: 'sea' })).be.null();
    should(equals({ a: 1, b: 'bee', c: 'sea' }, { a: 1, b: 'bee', c: null })).be.null();
    should(equals({ a: 1, b: 'bee', c: null }, { a: 1, b: 'bee', c: 'sea' })).be.null();
    should(equals({ a: null, b: 'bee', c: 'sea' }, { a: 1, b: 'bee', c: 'sea' })).be.null();
    should(equals({ a: 1, b: 'bee', c: 'sea' }, { a: null, b: 'bee', c: 'sea' })).be.null();
```
Suggest adding tests for null being in the first and late place in the object.

2025-03-31 18:17 UTC, hossenlopp commented on test/util/comparison-test.ts
> +    equals({ a: 1, b: null, c: 'sea' }, { a: 1, b: null, c: 'see' }).should.be.false();
```suggestion
    equals({ a: 1, b: null, c: 'sea' }, { a: 1, b: null, c: 'see' }).should.be.false();
    equals({ a: 1, b: 'bee', c: null }, { a: 1, b: 'bee', c: null }).should.be.true();
    equals({ a: 1, b: 'bee', c: null }, { a: 1, b: 'bea', c: null }).should.be.false();
    equals({ a: null, b: 'bee', c: 'sea' }, { a: null, b: 'bee', c: 'sea' }).should.be.true();
    equals({ a: null, b: 'bee', c: 'sea' }, { a: null, b: 'bee', c: 'see' }).should.be.false();
```
Suggest adding a few more tests for the situation null is first or last in the object.

2025-03-31 19:16 UTC, hossenlopp commented
lgtm

2025-03-31 19:17 UTC, hossenlopp approved these changes
👍

2025-03-31 19:17 UTC, merged